modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "CC-0"

[[mods]]
modId = "dynamicvillagertrades"
version = "${version}"
displayName = "Dynamic Villager Trades"
authors = "orlouge"
description = '''
Dynamic Villager Trades
'''
#logoFile = ""

[[dependencies.dynamicvillagertrades]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dynamicvillagertrades]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"